### ISSUE TITLE
SCSS - Npm - Gulp How to

### ISSUE THREAD

**Issue by stef-k** [understrap/understrap.github.io#2]
regarding holger1411/understrap#158, where to put the example in Developing with npm & Gulp section or in separate examples - how section/page?

Is this a signle or multi page project?

**Comment by holger1411** [comment]
it´s single page - if necessarry we can extend it - but for now a single page website seems to be okay.
Its okay if you extend / edit the "Developing with npm & Gulp" https://understrap.github.io/#developing
